# This file is machine-generated - editing it directly is not advised

julia_version = "1.12.6"
manifest_format = "2.0"
project_hash = "230be9d0e44d97f274741d7ed5073b81473bce16"

[[deps.PaperRebuild]]
path = "."
uuid = "70a6da1b-296e-4bc4-b705-f8de4306eaa2"
version = "0.1.0"
