name = "PaperRebuild"
uuid = "70a6da1b-296e-4bc4-b705-f8de4306eaa2"
version = "0.1.0"
authors = ["King <2668798565@qq.com>"]

[compat]
julia = "~1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
