include("r4_setup.jl")
include(joinpath(@__DIR__, "..", "test", "r4.jl"))
include(joinpath(@__DIR__, "..", "test", "r4_baseline.jl"))
include(joinpath(@__DIR__, "..", "test", "r4_bargaining.jl"))
include(joinpath(@__DIR__, "..", "test", "r4_tspa.jl"))
include(joinpath(@__DIR__, "..", "test", "r4_distributed.jl"))
